name: Release on Main Push

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Release Version
        id: set_version
        run: echo "RELEASE_VERSION=$(git rev-parse --short HEAD)" > $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_version.outputs.RELEASE_VERSION }}
          release_name: Release ${{ steps.set_version.outputs.RELEASE_VERSION }}
          body: |
            Changes in this release:
            - Add new feature
            - Fix bug

